# Auto-extracted generating script
# Produces: README.md
# Conda env: psoriasis-r   (run with this environment activated)
# Inputs (expected alongside / in data/): none
# Source artifact version: b32745eb-b5a8-4410-98fc-e00f1ca16620
# NOTE: absolute artifact paths rewritten to basenames; place named inputs in the same dir.
#------------------------------------------------------------

# README.md is a plain markdown file created via a file edit operation, not generated by R code.
# It was written directly as a file (FILE EDITED) with no R code producing it.
# The content is static markdown. Here is the R code to write it:

writeLines(c(
'# Psoriasis meta-analysis \xe2\x80\x94 reproducible pipeline',
'',
'Differential expression of **lesional psoriatic skin (PP) vs normal skin (NN)**,',
'built toward a STAT3-centred meta-analysis. This directory contains everything a',
'reviewer needs to regenerate our results from the raw public data, and everything',
'*we* need to rebuild our checkpoints after a disconnect.',
'',
'- **Study:** SRP035988 (Li et al.), accessed via **recount3**',
'- **Annotation:** Gencode v26 (recount3 \xe2\x80\x9cG026\xe2\x80\x9d), genome build GRCh38/hg38',
'- **Design:** NN (n=83) vs PP (n=95); limma-voom moderated t-test',
'- **Headline result:** 3,477 genes at BH-FDR < 0.05 **and** |log2FC| > 1',
'  (1,511 up, 1,966 down). STAT3 up +1.16 log2FC (~2.2x) with its IL-17 / SOCS3',
'  neighbourhood coherently up.',
'',
'---',
'',
'## 1. What\xe2\x80\x99s in this directory',
'',
'| File | Description |',
'|------|-------------|',
'| `psoriasis_pipeline.R`          | **Master script** \xe2\x80\x94 raw download \xe2\x86\x92 DE \xe2\x86\x92 figures, top to bottom |',
'| `dge_filt_norm.rds`             | Checkpoint 1: filtered + TMM-normalised DGEList (24,528 \xc3\x97 178) |',
'| `de_results_full.rds` / `.csv`  | Checkpoint 2: all 24,528 genes (logFC, p, adj.P.Val, qvalue, B) |',
'| `de_results_significant.csv`    | The 3,477 significant genes |',
'| `fig6_volcano.png`              | Volcano plot |',
'| `fig7_qvalue.png`               | p-value histogram + Storey q vs BH diagnostic |',
'| `whitepaper/`                   | White paper + method deep-dives (normalisation, DE) |',
'',
'## 2. Software environment',
'',
'Analysis runs in **R (>= 4.4)** with Bioconductor. We use a conda environment',
'(`psoriasis-r`) so the toolchain is pinned and portable.',
'',
'### Option A \xe2\x80\x94 recreate the conda environment (recommended)',
'